sonar.projectKey=api-qualidade-mini-fintech
sonar.projectName=api-qualidade-mini-fintech
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.exclusions=dist/**,node_modules/**
